modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT"
issueTrackerURL="https://github.com/TeamGalacticraft/DynamicDimensions/issues/"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://galacticraft.dev/"
logoFile="${mod_id}.png"
credits="Team Galacticraft"
authors="Team Galacticraft"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
    modId="badpackets"
mandatory = true
versionRange = "[0.4,)"
ordering = "NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
    side="BOTH"
