name: Maven Publish

on:
  push:
    branches: [ 'minecraft/*' ]

jobs:
  Publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Publish
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: publish
        env:
          PRE_RELEASE: true
          NEXUS_REPOSITORY_URL: ${{ secrets.NEXUS_RELEASE_URL }}
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
